[package]
name = "play-youtube"
version = "0.1.0"
description = "Play YouTube in your terminal!"
authors = ["LEGOlord208 <LEGOlord208@krake.one>"]
license = "MIT"

[dependencies]
tempdir = "0.3"
clap = "2.24"
ctrlc = "3.0"
image = "0.14"
terminal_size = "0.1"
lazy_static = "0.2"
time = "0.1"
ears = "0.4"
